// Generated by scripts/gen-api.mjs from clipper/platforms.py. Do not edit.
export const PLATFORM_NAME: Record<string, string> = {
  "tiktok": "TikTok",
  "instagram": "Instagram",
  "youtube": "YouTube",
  "x": "X",
  "facebook": "Facebook",
  "snapchat": "Snapchat",
  "threads": "Threads",
  "instagram_reels": "Instagram Reels",
  "youtube_shorts": "YouTube Shorts",
  "facebook_reels": "Facebook Reels",
  "snapchat_spotlight": "Snapchat Spotlight"
};
export const TARGETS: [string, string][] = [["tiktok", "TikTok"], ["instagram_reels", "Instagram Reels"], ["youtube_shorts", "YouTube Shorts"], ["x", "X"], ["facebook_reels", "Facebook Reels"], ["snapchat_spotlight", "Snapchat Spotlight"], ["threads", "Threads"]];
export const NO_STATS: string[] = ["facebook", "snapchat", "threads"];
