// Generated by scripts/gen-api.mjs from the FastAPI schema. Do not edit.
export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_api_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Visit
         * @description The page is open and in view (sent on load, every few minutes, and on return).
         *
         *     A new session starts after SESSION_GAP_MINUTES without one; the previous
         *     session's last activity becomes "last visit", so "since you were last here"
         *     covers the time away -- not the seconds since the last page load.
         */
        post: operations["visit_api_visit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaigns */
        get: operations["campaigns_api_campaigns_get"];
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_api_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign */
        get: operations["campaign_api_campaigns__name__get"];
        /** Edit Campaign */
        put: operations["edit_campaign_api_campaigns__name__put"];
        post?: never;
        /**
         * Delete Campaign
         * @description Only a campaign with no clips; one with clips is archived instead.
         */
        delete: operations["delete_campaign_api_campaigns__name__delete"];
        options?: never;
        head?: never;
        /** Update Campaign */
        patch: operations["update_campaign_api_campaigns__name__patch"];
        trace?: never;
    };
    "/api/campaigns/{name}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Form */
        get: operations["campaign_form_api_campaigns__name__form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/read-brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read Brief
         * @description Fill the New campaign form from a pasted brief (the configured AI model).
         */
        post: operations["read_brief_api_campaigns_read_brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Campaign
         * @description Read a pasted campaign brief and say how well it fits this user.
         */
        post: operations["check_campaign_api_campaigns_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/found": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Found Campaigns */
        get: operations["found_campaigns_api_found_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/found/{key}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Found */
        post: operations["check_found_api_found__key__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/found/{key}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Found */
        post: operations["dismiss_found_api_found__key__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clips */
        get: operations["clips_api_clips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clip */
        get: operations["clip_api_clips__clip_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Clip
         * @description To the trash: hidden at once, the file kept 30 days, then recycled.
         */
        delete: operations["delete_clip_api_clips__clip_id__delete"];
        options?: never;
        head?: never;
        /** Update Clip */
        patch: operations["update_clip_api_clips__clip_id__patch"];
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Posts */
        get: operations["posts_api_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark Submitted */
        put: operations["mark_submitted_api_posts_submitted_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}/submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Clip Submitted
         * @description Mark a clip submitted (or not): its status, and every post link it has.
         */
        put: operations["clip_submitted_api_clips__clip_id__submitted_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rate Clip
         * @description The user's 1-5 verdict on a clip, and why; what the learner learns from.
         */
        put: operations["rate_clip_api_clips__clip_id__rating_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learning */
        get: operations["learning_api_learning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Post History */
        get: operations["post_history_api_posts_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Accounts */
        get: operations["get_accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{platform}/{account}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect */
        delete: operations["disconnect_api_accounts__platform___account__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/tiktok/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tiktok Connect State */
        get: operations["tiktok_connect_state_api_accounts_tiktok_connect_get"];
        put?: never;
        /**
         * Tiktok Connect
         * @description Start TikTok's login; the page opens the returned consent link.
         */
        post: operations["tiktok_connect_api_accounts_tiktok_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/instagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Instagram Connect */
        post: operations["instagram_connect_api_accounts_instagram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Setup */
        get: operations["get_setup_api_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Keys */
        put: operations["put_keys_api_setup_keys_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/test-ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Ai */
        post: operations["test_ai_api_setup_test_ai_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** System Check */
        post: operations["system_check_api_setup_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal
         * @description Show the clip's file in Explorer, selected, e.g. to drag it into an upload page.
         */
        post: operations["reveal_api_clips__clip_id__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Clip */
        post: operations["restore_clip_api_clips__clip_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload
         * @description Stream an uploaded video into Clipper's downloads folder (no size limit).
         */
        put: operations["upload_api_uploads__filename__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect Link
         * @description What a shared footage link holds, before downloading it.
         */
        post: operations["inspect_link_api_imports_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imports */
        get: operations["list_imports_api_imports_get"];
        put?: never;
        /**
         * Start Import
         * @description Download a shared link's videos into Clipper's uploads, in the background.
         */
        post: operations["start_import_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Start Job */
        post: operations["start_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Video
         * @description A source video for the page's player (manual mode), with seeking.
         */
        get: operations["source_video_api_sources_video_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thumb/{clip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Thumb
         * @description A still of the clip at 1.5s (hook on screen), made once and kept.
         */
        get: operations["thumb_thumb__clip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Post
         * @description A post link pasted by hand, for when the sync hasn't found the post yet.
         */
        post: operations["add_post_api_clips__clip_id__posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{clip_id}/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proof Pack
         * @description A zip to send a campaign if it rejects the clip: brief, checks, posts, views, clip.
         */
        get: operations["proof_pack_media__clip_id__proof_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{clip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Media
         * @description The clip's video: streamed for playing, or as a named file to save.
         */
        get: operations["media_media__clip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_research_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Threads */
        get: operations["threads_api_research_threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thread */
        get: operations["thread_api_research_threads__thread_id__get"];
        put?: never;
        post?: never;
        /** Delete Thread */
        delete: operations["delete_thread_api_research_threads__thread_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Ask in a conversation (a new one without `thread_id`); returns it with the answer.
         */
        post: operations["ask_api_research_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            /** Id */
            id: string;
            /** Platform */
            platform: string;
            /** Connected */
            connected: boolean;
            /** Handle */
            handle: string;
            /** Health */
            health: string;
            /** Detail */
            detail: string;
            /** Expires In Days */
            expires_in_days?: number | null;
        };
        /** Band */
        Band: {
            /** Label */
            label: string;
            /** Clips */
            clips: number;
            /** Avg Rating */
            avg_rating?: number | null;
            /** Rated */
            rated: number;
            /** Median Views */
            median_views?: number | null;
        };
        /** Brief */
        Brief: {
            /** Min Seconds */
            min_seconds: number;
            /** Max Seconds */
            max_seconds: number;
            /** Required Text */
            required_text: string;
            /** Hashtags */
            hashtags: string[];
            /** Credit */
            credit: string;
            /** Captions */
            captions: string[];
            /** Hook Texts */
            hook_texts: string[];
            /** Original Audio */
            original_audio: boolean;
            /** Long Description */
            long_description: boolean;
            /** Min Payout Usd */
            min_payout_usd?: number | null;
            /** Max Payout Usd */
            max_payout_usd?: number | null;
            /** Campaign Url */
            campaign_url: string;
            /** Deadline */
            deadline: string;
            /** Authorization */
            authorization: string;
            /** Notes */
            notes: string;
        };
        /** Campaign */
        Campaign: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /**
             * Marketplace
             * @default
             */
            marketplace: string;
            /** Has Brief */
            has_brief: boolean;
            /** Archived */
            archived: boolean;
            /** Auto Post */
            auto_post: boolean | null;
            /** Platforms */
            platforms: string[];
            /** Reward Per 1K Usd */
            reward_per_1k_usd?: number | null;
            /**
             * Max Clips
             * @default 8
             */
            max_clips: number;
            /** Clips */
            clips: number;
            counts: components["schemas"]["CampaignCounts"];
            /** Views */
            views: number;
            /** Est Earnings */
            est_earnings?: number | null;
            /** To Submit */
            to_submit: number;
            /** Last Post */
            last_post?: string | null;
            /**
             * Campaign Url
             * @default
             */
            campaign_url: string;
        };
        /** CampaignCheck */
        CampaignCheck: {
            form: components["schemas"]["CampaignForm"];
            fit: components["schemas"]["Fit"];
        };
        /** CampaignCounts */
        CampaignCounts: {
            /**
             * Ready
             * @default 0
             */
            ready: number;
            /**
             * Posted
             * @default 0
             */
            posted: number;
            /**
             * Submitted
             * @default 0
             */
            submitted: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
        };
        /** CampaignDetail */
        CampaignDetail: {
            campaign: components["schemas"]["Campaign"];
            brief: components["schemas"]["Brief"] | null;
            /** Clips */
            clips: components["schemas"]["Clip"][];
        };
        /**
         * CampaignForm
         * @description What the New campaign / Edit campaign page shows.
         */
        CampaignForm: {
            /** Title */
            title: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Marketplace
             * @default
             */
            marketplace: string;
            /**
             * Campaign Url
             * @default
             */
            campaign_url: string;
            /** Reward Per 1K Usd */
            reward_per_1k_usd?: number | null;
            /** Min Payout Usd */
            min_payout_usd?: number | null;
            /** Max Payout Usd */
            max_payout_usd?: number | null;
            /**
             * Deadline
             * @default
             */
            deadline: string;
            /**
             * Source Authorization
             * @default
             */
            source_authorization: string;
            /** Platform Targets */
            platform_targets?: string[];
            /**
             * Content Type
             * @default scripted
             * @enum {string}
             */
            content_type: "scripted" | "podcast" | "other";
            /**
             * Min Seconds
             * @default 15
             */
            min_seconds: number;
            /**
             * Max Seconds
             * @default 60
             */
            max_seconds: number;
            /**
             * Selection Focus
             * @default
             */
            selection_focus: string;
            /**
             * Required Caption Text
             * @default
             */
            required_caption_text: string;
            /** Required Hashtags */
            required_hashtags?: string[];
            /**
             * Only Required Hashtags
             * @default false
             */
            only_required_hashtags: boolean;
            /**
             * Required Credit Text
             * @default
             */
            required_credit_text: string;
            /** Fallback Captions */
            fallback_captions?: string[];
            /**
             * Fixed Captions
             * @default false
             */
            fixed_captions: boolean;
            /** Hook Texts */
            hook_texts?: string[];
            /**
             * Hook Overlay
             * @default true
             */
            hook_overlay: boolean;
            /**
             * Keep Original Audio
             * @default false
             */
            keep_original_audio: boolean;
            /**
             * Brief Rules
             * @default
             */
            brief_rules: string;
            /**
             * Long Description
             * @default true
             */
            long_description: boolean;
            /**
             * Description Context
             * @default
             */
            description_context: string;
            /** Description Keywords */
            description_keywords?: string[];
            /**
             * Max Clips Per Source
             * @default 6
             */
            max_clips_per_source: number;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Clip */
        Clip: {
            /** Id */
            id: number;
            /** Campaign */
            campaign: string;
            /** Title */
            title: string;
            /** Hook */
            hook: string;
            /** Caption */
            caption: string;
            /** Duration S */
            duration_s?: number | null;
            /** Source Title */
            source_title: string;
            /** Status */
            status: string;
            /** Marked */
            marked: string;
            /** Notes */
            notes: string;
            /** Created At */
            created_at: string;
            /** File Exists */
            file_exists: boolean;
            /** Video */
            video: string;
            /** Thumb */
            thumb: string;
            /** Posts */
            posts: components["schemas"]["Post"][];
            /** Score */
            score?: number | null;
            /**
             * Rubric
             * @default {}
             */
            rubric: {
                [key: string]: number;
            };
            /** Pool */
            pool?: number | null;
            /** Pool Rank */
            pool_rank?: number | null;
            /**
             * Picked By
             * @default unknown
             */
            picked_by: string;
            /** Rating */
            rating?: number | null;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            proof?: components["schemas"]["Proof"] | null;
            /**
             * Watching
             * @default false
             */
            watching: boolean;
            /**
             * Duplicates
             * @default []
             */
            duplicates: components["schemas"]["Duplicate"][];
        };
        /** Dimension */
        Dimension: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Default */
            default: number;
            /** Learned */
            learned: number;
            /** Agreement */
            agreement?: number | null;
        };
        /** Duplicate */
        Duplicate: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** How */
            how: string;
            /** Posted On */
            posted_on: string[];
        };
        /** Fit */
        Fit: {
            /** Verdict */
            verdict: string;
            /** Checks */
            checks: components["schemas"]["FitCheck"][];
            /** Per Post Usd */
            per_post_usd?: number | null;
            /** Checked At */
            checked_at: string;
        };
        /** FitCheck */
        FitCheck: {
            /** Ok */
            ok?: boolean | null;
            /** Text */
            text: string;
        };
        /** FoundCampaign */
        FoundCampaign: {
            /** Key */
            key: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /** Owner */
            owner: string;
            /** Rate */
            rate: string;
            /** Rate Per 1K Usd */
            rate_per_1k_usd?: number | null;
            /** Platforms */
            platforms: string[];
            /** Budget */
            budget: string;
            /** Deadline */
            deadline: string;
            /** Link */
            link: string;
            /** Fit */
            fit: string;
            /** Why */
            why: string;
            /** Found At */
            found_at: string;
            /** Dismissed */
            dismissed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Home */
        Home: {
            metrics: components["schemas"]["Metrics"];
            since: components["schemas"]["SinceLastVisit"] | null;
            pipeline: components["schemas"]["CampaignCounts"];
            /** First Run */
            first_run: {
                [key: string]: boolean;
            };
        };
        /** Learning */
        Learning: {
            /** Active */
            active: boolean;
            /** Rated */
            rated: number;
            /** Unrated */
            unrated: number;
            /** Scored And Rated */
            scored_and_rated: number;
            /** Agreement */
            agreement?: number | null;
            /** Agreement Verdict */
            agreement_verdict: string;
            /** With Views */
            with_views: number;
            /** Views Agreement */
            views_agreement?: number | null;
            /** Views Verdict */
            views_verdict: string;
            /** Rating Vs Views */
            rating_vs_views?: number | null;
            /** Bands */
            bands: components["schemas"]["Band"][];
            /** Dimensions */
            dimensions: components["schemas"]["Dimension"][];
            /** Reasons */
            reasons: components["schemas"]["ReasonCount"][];
            /** Taste */
            taste: string;
            /** Weights N */
            weights_n: number;
            /** Min For Weights */
            min_for_weights: number;
            /** Min For Agreement */
            min_for_agreement: number;
            /** Reason Labels */
            reason_labels: {
                [key: string]: string;
            };
        };
        /** Message */
        Message: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Created At */
            created_at: string;
        };
        /** Metrics */
        Metrics: {
            /** Est Earnings */
            est_earnings: number | null;
            /** Views */
            views: number;
            /** Posts */
            posts: number;
            /** Median Views */
            median_views: number | null;
            /** To Submit */
            to_submit: number;
            /** Ready */
            ready: number;
        };
        /** Post */
        Post: {
            /** Platform */
            platform: string;
            /** Account */
            account: string;
            /** Url */
            url: string;
            /** Campaign */
            campaign: string;
            /** Clip */
            clip: number;
            /** Clip Title */
            clip_title: string;
            /** Posted At */
            posted_at?: string | null;
            /** Age Hours */
            age_hours?: number | null;
            /**
             * Settling
             * @default false
             */
            settling: boolean;
            /** Views */
            views?: number | null;
            /** Likes */
            likes?: number | null;
            /** Comments */
            comments?: number | null;
            /** Shares */
            shares?: number | null;
            /** Saves */
            saves?: number | null;
            /** Avg Watch S */
            avg_watch_s?: number | null;
            /** Watched Full Pct */
            watched_full_pct?: number | null;
            /** Skip Rate Pct */
            skip_rate_pct?: number | null;
            /** X Median */
            x_median?: number | null;
            /** Est Earnings */
            est_earnings?: number | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Posted Caption */
            posted_caption?: string | null;
        };
        /** Proof */
        Proof: {
            /** Saved At */
            saved_at?: string | null;
            /**
             * Late
             * @default false
             */
            late: boolean;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Posted Ok */
            posted_ok?: boolean | null;
        };
        /** ReasonCount */
        ReasonCount: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** ResearchStatus */
        ResearchStatus: {
            /** Plan */
            plan: string;
            /** Can Research */
            can_research: boolean;
            /** Ai */
            ai: boolean;
            /** Web */
            web: boolean;
        };
        /** Setup */
        Setup: {
            /** Ai Ready */
            ai_ready: boolean;
            /** Ai Backend */
            ai_backend: string;
            /** Ai Detail */
            ai_detail: string;
            /** Keys */
            keys: {
                [key: string]: boolean;
            };
            /** Tiktok App */
            tiktok_app: boolean;
            /** Tiktok Connect */
            tiktok_connect: {
                [key: string]: string;
            };
        };
        /** SinceLastVisit */
        SinceLastVisit: {
            /** Since */
            since: string;
            /** Views Gained */
            views_gained: number;
            /** New Posts */
            new_posts: number;
            top_mover?: components["schemas"]["Post"] | null;
            /**
             * Top Mover Gain
             * @default 0
             */
            top_mover_gain: number;
        };
        /** Source */
        Source: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** Status */
        Status: {
            /** Last Synced */
            last_synced: string;
            /** Syncing */
            syncing: boolean;
            /** Sync Minutes */
            sync_minutes: number;
            /** Problems */
            problems: string[];
            /** Auto Post */
            auto_post: boolean;
            /** Accounts */
            accounts: components["schemas"]["Account"][];
        };
        /** Thread */
        Thread: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** ThreadDetail */
        ThreadDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["Message"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    home_api_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
        };
    };
    visit_api_visit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    campaigns_api_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"][];
                };
            };
        };
    };
    create_campaign_api_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_api_campaigns__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_campaign_api_campaigns__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_campaign_api_campaigns__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_campaign_api_campaigns__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_form_api_campaigns__name__form_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignForm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_brief_api_campaigns_read_brief_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignForm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_campaign_api_campaigns_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    found_campaigns_api_found_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundCampaign"][];
                };
            };
        };
    };
    check_found_api_found__key__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_found_api_found__key__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clips_api_clips_get: {
        parameters: {
            query?: {
                campaign?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clip"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clip_api_clips__clip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_clip_api_clips__clip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_clip_api_clips__clip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    posts_api_posts_get: {
        parameters: {
            query?: {
                campaign?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_submitted_api_posts_submitted_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clip_submitted_api_clips__clip_id__submitted_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_clip_api_clips__clip_id__rating_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    learning_api_learning_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Learning"];
                };
            };
        };
    };
    post_history_api_posts_history_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    disconnect_api_accounts__platform___account__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                account: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tiktok_connect_state_api_accounts_tiktok_connect_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    tiktok_connect_api_accounts_tiktok_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    instagram_connect_api_accounts_instagram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_setup_api_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setup"];
                };
            };
        };
    };
    put_keys_api_setup_keys_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_ai_api_setup_test_ai_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    system_check_api_setup_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    reveal_api_clips__clip_id__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_clip_api_clips__clip_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    upload_api_uploads__filename__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_link_api_imports_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imports_api_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    start_import_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    start_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_video_api_sources_video_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    thumb_thumb__clip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_post_api_clips__clip_id__posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proof_pack_media__clip_id__proof_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_media__clip_id__get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                clip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_research_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchStatus"];
                };
            };
        };
    };
    threads_api_research_threads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
        };
    };
    thread_api_research_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_api_research_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_research_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
