"""The full `clipper run` against real synthesised speech.

Deterministic: the mock LLM backend scores from the candidate text, so the same
fixture always produces the same picks.

Every read-only assertion shares one `standard_run`. Running the whole pipeline
per test -- ingest, transcription, scoring, renders, QA -- pushed the suite past
ten minutes for no extra coverage. Tests that need a *different* configuration
still perform their own run, against a data root shared across the module so the
stage cache makes the repeat cheap.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import pytest

from clipper import runner
from clipper.config import CampaignConfig, Config
from clipper.ingest.probe import probe

from ..conftest import needs_ffmpeg
from ..fixtures import speech

pytestmark = [pytest.mark.slow, needs_ffmpeg]

needs_sapi = pytest.mark.skipif(not speech.sapi_available(), reason="Windows SAPI unavailable")


@pytest.fixture(scope="module")
def cfg() -> Config:
    base = Config.load()
    return base.model_copy(update={
        "transcription": base.transcription.model_copy(update={"model": "small"}),
        "llm": base.llm.model_copy(update={"backend": "mock", "batch_size": 8}),
    })


@pytest.fixture(scope="module")
def campaign() -> CampaignConfig:
    return CampaignConfig.model_validate({
        "name": "test-campaign",
        "source_authorization": "Locally synthesised fixture, generated by this project",
        "duration": {"min_seconds": 15, "max_seconds": 60},
        "required_hashtags": ["#example"],
        "required_credit_text": "Source: @testcreator",
    })


@pytest.fixture(scope="module")
def long_source(media_cache, module_data_root):
    """~3.5 minutes, so more than one non-overlapping clip can be placed."""
    return speech.speech_video(list(speech.LONG_SCRIPT), name="long")


@pytest.fixture(scope="module")
def standard_run(long_source, cfg, campaign, module_data_root, tmp_path_factory):
    """One full run, shared by every read-only assertion below."""
    out = Path(tmp_path_factory.mktemp("standard_run"))
    return runner.run(str(long_source.video), config=cfg, campaign=campaign,
                      out_root=out, top=3, draft=True, backend_override="mock")


@needs_sapi
class TestRun:
    def test_produces_clips_and_every_output_file(self, standard_run):
        result = standard_run
        assert result.clip_count >= 1
        for key in ("manifest_csv", "manifest_json", "performance_log", "report_md"):
            assert result.outputs[key].is_file(), key
        for record in result.accepted:
            assert record.file.is_file()

    def test_rendered_clips_are_conformant(self, standard_run, campaign):
        for record in standard_run.accepted:
            media = probe(record.file)
            assert (media.width, media.height) == (540, 960)  # --draft size
            assert media.has_audio
            assert campaign.duration.min_seconds <= media.duration <= campaign.duration.max_seconds

    def test_accepted_clips_all_passed_qa_and_compliance(self, standard_run):
        for record in standard_run.accepted:
            assert record.qa.status != "fail", [c.detail for c in record.qa.failures]
            assert record.compliance.status == "pass", record.compliance.summary()

    def test_clip_ids_and_filenames_are_unique(self, standard_run):
        """Rejected clips used to reuse the rank, colliding on both."""
        everything = standard_run.accepted + standard_run.rejected
        ids = [r.plan.clip_id for r in everything]
        names = [r.file.name for r in everything]
        assert len(set(ids)) == len(ids), ids
        assert len(set(names)) == len(names), names

    def test_selected_clips_do_not_overlap(self, standard_run):
        spans = [(r.plan.start, r.plan.end) for r in standard_run.accepted]
        for i, (a_start, a_end) in enumerate(spans):
            for b_start, b_end in spans[i + 1:]:
                assert a_start >= b_end or b_start >= a_end, spans

    def test_the_campaign_caption_and_credit_are_applied(self, standard_run):
        assert standard_run.accepted
        for record in standard_run.accepted:
            assert "#example" in record.plan.hashtags
            assert "Source: @testcreator" in record.plan.suggested_caption

    def test_the_manifest_matches_the_accepted_clips(self, standard_run):
        rows = list(csv.DictReader(
            standard_run.outputs["manifest_csv"].open(encoding="utf-8")))
        assert len(rows) == standard_run.clip_count
        assert {r["clip_id"] for r in rows} == {r.plan.clip_id for r in standard_run.accepted}

    def test_the_json_manifest_records_the_authorization(self, standard_run, campaign):
        data = json.loads(standard_run.outputs["manifest_json"].read_text(encoding="utf-8"))
        assert data["source_authorization"] == campaign.source_authorization

    def test_the_performance_log_joins_back_to_the_manifest(self, standard_run):
        from clipper.learn import log as perf

        rows = perf.read(standard_run.outputs["performance_log"])
        mine = [r for r in rows if r["source_id"] == standard_run.info.source_id]
        assert {r["clip_id"] for r in mine} == {r.plan.clip_id for r in standard_run.accepted}
        assert {r["candidate_id"] for r in mine} == {
            r.plan.candidate_id for r in standard_run.accepted}

    def test_timings_are_recorded(self, standard_run):
        assert standard_run.timings["total"] > 0
        assert "render_and_qa" in standard_run.timings

    def test_the_report_names_each_clip(self, standard_run):
        report = standard_run.outputs["report_md"].read_text(encoding="utf-8")
        for record in standard_run.accepted:
            assert record.plan.clip_id in report

    def test_the_campaign_clip_cap_is_respected(self, long_source, cfg,
                                                module_data_root, tmp_path):
        capped = CampaignConfig.model_validate({
            "name": "capped",
            "source_authorization": "Locally synthesised fixture for testing",
            "max_clips_per_source": 1,
        })
        result = runner.run(str(long_source.video), config=cfg, campaign=capped,
                            out_root=tmp_path, top=5, draft=True,
                            backend_override="mock")
        assert result.clip_count <= 1


@needs_sapi
class TestQualityGateEndToEnd:
    def test_an_unreachable_bar_produces_no_clips_and_says_so(
        self, long_source, cfg, campaign, module_data_root, tmp_path
    ):
        """BUILD_BRIEF.md section 1: returning nothing beats returning filler.

        `min_llm_total` is capped at 10.0, so this is only unreachable when no
        candidate scored a perfect 10. Checked rather than assumed.
        """
        from clipper import pipeline

        scored = pipeline.score(str(long_source.video), cfg, backend_override="mock")
        live = [s for s in scored.scored.scored if not s.dropped and "llm" in s.raw]
        assert live, "fixture must produce LLM-scored candidates"
        if max(s.raw["llm"] for s in live) >= 10.0:
            pytest.skip("a candidate scored a perfect 10; no bar can exceed it")

        strict = cfg.model_copy(update={
            "selection": cfg.selection.model_copy(update={"min_llm_total": 10.0})
        })
        result = runner.run(str(long_source.video), config=strict, campaign=campaign,
                            out_root=tmp_path, top=3, draft=True,
                            backend_override="mock")
        assert result.clip_count == 0
        assert "quality bar" in result.selection_note

        report = result.outputs["report_md"].read_text(encoding="utf-8")
        assert "No clips" in report
        assert "better than returning filler" in report

    def test_the_stop_reason_states_a_real_outcome(self, standard_run):
        """It used to attribute every rejection to min_llm_total, reporting
        '27 scored below min_llm_total' on a run where only 5 had."""
        note = standard_run.selection_note
        assert note
        assert any(phrase in note for phrase in
                   ("reached the requested", "quality bar", "produced")), note


@needs_sapi
class TestQAReplacement:
    """A clip that fails QA must be replaced by the next-best *reserve*.

    Reserves only ever come from candidates that already cleared the quality
    gate, so a replacement can never quietly substitute filler.
    """

    @staticmethod
    def _fail_first(monkeypatch):
        from clipper.models import QACheck, QAReport
        from clipper.qa import checks as qa_checks

        real_check = qa_checks.check_clip
        calls = {"n": 0}

        def failing_first(path, context, qa, render):
            calls["n"] += 1
            if calls["n"] == 1:
                return QAReport(clip_id=context.plan.clip_id, file=str(path), checks=[
                    QACheck(name="black_frames", status="fail",
                            detail="injected failure for the replacement test")])
            return real_check(path, context, qa, render)

        monkeypatch.setattr("clipper.runner.check_clip", failing_first)

    def test_a_failure_is_replaced_and_fully_recorded(
        self, long_source, cfg, campaign, module_data_root, tmp_path, monkeypatch
    ):
        self._fail_first(monkeypatch)
        result = runner.run(str(long_source.video), config=cfg, campaign=campaign,
                            out_root=tmp_path, top=1, draft=True,
                            backend_override="mock")

        assert len(result.rejected) == 1
        assert result.clip_count == 1, "a reserve should have filled the slot"

        rejected = result.rejected[0]
        assert rejected.file.parent.name == "rejected"
        reason = rejected.file.with_suffix(".reason.json")
        assert reason.is_file()
        data = json.loads(reason.read_text(encoding="utf-8"))
        assert data["qa_failures"][0]["check"] == "black_frames"

        # The replacement must be a genuinely different moment.
        assert result.accepted[0].plan.candidate_id != rejected.plan.candidate_id
