"""The platforms Clipper knows, in one place (D147).

Posts, campaign targets, links, names and what each can report were scattered over a dozen files, each
with its own copy of "TikTok, Instagram, YouTube, X". To support another platform, add a row here:
the config's targets, the post-link parser, the names on the page and the campaign editor's buttons
all follow (the page gets them from `typescript()`, written by `npm run gen:api`).

`stats`: its official API gives Clipper a post's numbers (False: the link is filed for submitting, and
the numbers are read in its own app). `connect`: an account can be connected on the Accounts page.
Facebook, Snapchat and Threads are link-only: they have no official API that gives them.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Platform:
    id: str                    # a post's platform: "instagram"
    name: str                  # "Instagram"
    target: str                # a campaign's key for posting there: "instagram_reels"
    target_name: str           # "Instagram Reels"
    hosts: tuple[str, ...]     # the domains a post link is on
    stats: bool = True
    connect: bool = True


REGISTRY: tuple[Platform, ...] = (
    Platform("tiktok", "TikTok", "tiktok", "TikTok", ("tiktok.com",)),
    Platform("instagram", "Instagram", "instagram_reels", "Instagram Reels", ("instagram.com",)),
    Platform("youtube", "YouTube", "youtube_shorts", "YouTube Shorts", ("youtube.com", "youtu.be")),
    Platform("x", "X", "x", "X", ("x.com", "twitter.com")),
    Platform("facebook", "Facebook", "facebook_reels", "Facebook Reels", ("facebook.com", "fb.watch"), stats=False, connect=False),
    Platform("snapchat", "Snapchat", "snapchat_spotlight", "Snapchat Spotlight", ("snapchat.com",), stats=False, connect=False),
    Platform("threads", "Threads", "threads", "Threads", ("threads.net", "threads.com"), stats=False, connect=False),
)

#: What a campaign can target, in the order the editor shows them.
TARGETS: tuple[str, ...] = tuple(p.target for p in REGISTRY)
#: Names under both the account key ("instagram") and the campaign target ("instagram_reels").
NAMES: dict[str, str] = {**{p.id: p.name for p in REGISTRY}, **{p.target: p.name for p in REGISTRY}}
#: A post's platform -> the campaign target it posts for, and back.
TARGET_OF: dict[str, str] = {p.id: p.target for p in REGISTRY}
PLATFORM_OF: dict[str, str] = {p.target: p.id for p in REGISTRY}
#: Post-link domains -> platform.
HOSTS: dict[str, str] = {host: p.id for p in REGISTRY for host in p.hosts}
LINK_ONLY: tuple[str, ...] = tuple(p.id for p in REGISTRY if not p.stats)


def typescript() -> str:
    """The registry as the page's constants (src/api/platforms.gen.ts)."""
    import json

    names = {**{p.id: p.name for p in REGISTRY}, **{p.target: p.target_name for p in REGISTRY}}
    return ("// Generated by scripts/gen-api.mjs from clipper/platforms.py. Do not edit.\n"
            f"export const PLATFORM_NAME: Record<string, string> = {json.dumps(names, indent=2)};\n"
            f"export const TARGETS: [string, string][] = {json.dumps([[p.target, p.target_name] for p in REGISTRY])};\n"
            f"export const NO_STATS: string[] = {json.dumps(list(LINK_ONLY))};\n")
