// Generates src/api/schema.d.ts from the FastAPI app's OpenAPI schema, so a
// renamed or removed backend field breaks the build instead of the page.
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../../../../..");
const python = resolve(repo, ".venv/Scripts/python.exe");
const spec = execFileSync(python, ["-W", "ignore", "-c",
  "import json; from clipper.studio.server import create_app; print(json.dumps(create_app().openapi()))"],
  { cwd: repo, encoding: "utf8" });

const ast = await openapiTS(JSON.parse(spec));
const out = resolve(here, "../src/api/schema.d.ts");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, "// Generated by scripts/gen-api.mjs from the FastAPI schema. Do not edit.\n" + astToString(ast));
console.log("wrote", out);

// The platforms (clipper/platforms.py) as the page's constants.
const platforms = execFileSync(python, ["-W", "ignore", "-c", "from clipper.platforms import typescript; print(typescript(), end='')"],
  { cwd: repo, encoding: "utf8" });
writeFileSync(resolve(here, "../src/api/platforms.gen.ts"), platforms);
console.log("wrote platforms.gen.ts");
